/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blogapplication;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Morhaf
 */
public class AngeTillganglighet extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;
    private int motesId;
    private ArrayList<String> lista;
    private ArrayList<String> listaSTid;
    private int userId;
    /**
     * Creates new form AngeTillganglighet
     */
    public AngeTillganglighet(int userId, int motesId) {
        dataHanterare = new DataHanterare();
        databasen = DataHanterare.dataHanterare();
        this.setLocationRelativeTo(null);
        initComponents();
        this.motesId = motesId;
        this.userId=userId;
    }
    
    
    private void fyllDatumTid(){
        try{
           String namn=dataHanterare.getFullNamn(userId);
           lblanvnamn.setText(namn);
           String motesnamn= dataHanterare.getMotesnamn(motesId);
           lblmotesNamn.setText(motesnamn);
           lista = databasen.fetchColumn("SELECT DATUM FROM Anvandare_moten WHERE mostesid = "+motesId);
           listaSTid=databasen.fetchColumn("SELECT sluttid FROM Anvandare_moten WHERE mostesid = "+motesId);
           String slt1=listaSTid.get(0);
           String slt2=listaSTid.get(1);
           String slt3=listaSTid.get(2);
           for(int i = 0; i < lista.size(); i++){
              String datum = lista.get(i).substring(0,10);
              String tid = lista.get(i).substring(11,16);
              lblD1.setText(lista.get(0).substring(0,10));
              lblD2.setText(lista.get(1).substring(0,10));
              lblD3.setText(lista.get(2).substring(0,10));
              lblStt1.setText(lista.get(0).substring(11,16));
              lblStt2.setText(lista.get(1).substring(11,16));
              lblStt3.setText(lista.get(2).substring(11,16));
           }
           lblSlt1.setText(slt1);
           lblSlt2.setText(slt2);
           lblSlt3.setText(slt3);
        }
        catch(InfException e){
           JOptionPane.showMessageDialog(null, "det gick inte att hämta datumen från databasen");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblD1 = new javax.swing.JLabel();
        lblD2 = new javax.swing.JLabel();
        lblD3 = new javax.swing.JLabel();
        lblStt1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSlt1 = new javax.swing.JLabel();
        lblSlt2 = new javax.swing.JLabel();
        lblStt2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSlt3 = new javax.swing.JLabel();
        lblStt3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAngeTillganglighet = new javax.swing.JButton();
        lblmotesNamn = new javax.swing.JLabel();
        lblanvnamn = new javax.swing.JLabel();
        kan1 = new javax.swing.JCheckBox();
        kan2 = new javax.swing.JCheckBox();
        kan3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNamn.setText("Välkommen");

        jLabel1.setText(" Välj de tiderna som passar dig för mötet:");

        lblD1.setText("Datum1");

        lblD2.setText("Datum2");

        lblD3.setText("Datum3");

        lblStt1.setText("stt1");

        jLabel2.setText("-");

        lblSlt1.setText("slt1");

        lblSlt2.setText("slt2");

        lblStt2.setText("stt2");

        jLabel3.setText("-");

        lblSlt3.setText("slt3");

        lblStt3.setText("stt3");

        jLabel4.setText("-");

        btnAngeTillganglighet.setText("Ange tillgänglighet");
        btnAngeTillganglighet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngeTillganglighetActionPerformed(evt);
            }
        });

        lblmotesNamn.setText("motesnamn");

        lblanvnamn.setText("användarnamn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblD2))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSlt2))
                    .addComponent(lblD1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSlt1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblStt3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSlt3))
                    .addComponent(lblD3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kan3)
                    .addComponent(kan1)
                    .addComponent(kan2)
                    .addComponent(btnAngeTillganglighet)))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmotesNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNamn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblanvnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(lblanvnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblmotesNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStt1)
                            .addComponent(jLabel2)
                            .addComponent(lblSlt1)))
                    .addComponent(kan1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(69, 69, 69)
                .addComponent(lblD2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStt2)
                            .addComponent(jLabel3)
                            .addComponent(lblSlt2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(kan2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblD3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStt3)
                            .addComponent(jLabel4)
                            .addComponent(lblSlt3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kan3)
                        .addGap(66, 66, 66)))
                .addComponent(btnAngeTillganglighet)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       fyllDatumTid();
    }//GEN-LAST:event_formWindowOpened

    private void btnAngeTillganglighetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngeTillganglighetActionPerformed
        boolean ett = kan1.isSelected();
        boolean tva = kan2.isSelected();
        boolean tre = kan3.isSelected();  
        
        if(ett){
            try{
                databasen.update("UPDATE Anvandare_moten SET KAN = 'Y' WHERE DATUM LIKE '"+lblD1.getText() + " " + lblStt1.getText()+"%' AND Sluttud='"+lblSlt1.getText()+"' And MostesId = '"+motesId+"' AND deltagare = '"+userId+"';");
            }
            catch(InfException e){
                JOptionPane.showMessageDialog(null, "1");
            }
        }
        else{
            try{
                databasen.update("UPDATE Anvandare_moten SET KAN = 'N' WHERE DATUM LIKE '"+lblD1.getText() + " " + lblStt1.getText()+"%' AND Sluttud='"+lblSlt1.getText()+"' And MostesId = '"+motesId+"' AND deltagare = '"+userId+"';");
            }
            catch(InfException e){
                JOptionPane.showMessageDialog(null, "2");
            }
        }
        
        if(tva){
            try{
                databasen.update("UPDATE Anvandare_moten SET KAN = 'Y' WHERE DATUM LIKE '"+lblD2.getText() + " " + lblStt2.getText()+"%' AND Sluttud='"+lblSlt2.getText()+"' And MostesId = '"+motesId+"' AND deltagare = '"+userId+"';");
            }
            catch(InfException e){
                JOptionPane.showMessageDialog(null, "1");
            }
        }
        else{
            try{
                databasen.update("UPDATE Anvandare_moten SET KAN = 'N' WHERE DATUM LIKE '"+lblD2.getText() + " " + lblStt2.getText()+"%' AND Sluttud='"+lblSlt2.getText()+"' And MostesId = '"+motesId+"' AND deltagare = '"+userId+"';");
            }
            catch(InfException e){
                JOptionPane.showMessageDialog(null, "2");
            }
        }
        
        if(tre){
        try{
                databasen.update("UPDATE Anvandare_moten SET KAN = 'Y' WHERE DATUM LIKE '"+lblD3.getText() + " " + lblStt3.getText()+"%' AND Sluttud='"+lblSlt3.getText()+"' And MostesId = '"+motesId+"' AND deltagare = '"+userId+"';");
            }
            catch(InfException e){
                JOptionPane.showMessageDialog(null, "1");
            }
        }
        else{
            try{
                databasen.update("UPDATE Anvandare_moten SET KAN = 'N' WHERE DATUM LIKE '"+lblD3.getText() + " " + lblStt3.getText()+"%' AND Sluttud='"+lblSlt3.getText()+"' And MostesId = '"+motesId+"' AND deltagare = '"+userId+"';");
            }
            catch(InfException e){
                JOptionPane.showMessageDialog(null, "2");
            }
        }
        JOptionPane.showMessageDialog(null, "Dina svar har nu skickats till mötesarrangören.");
    }//GEN-LAST:event_btnAngeTillganglighetActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAngeTillganglighet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox kan1;
    private javax.swing.JCheckBox kan2;
    private javax.swing.JCheckBox kan3;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblD3;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblSlt1;
    private javax.swing.JLabel lblSlt2;
    private javax.swing.JLabel lblSlt3;
    private javax.swing.JLabel lblStt1;
    private javax.swing.JLabel lblStt2;
    private javax.swing.JLabel lblStt3;
    private javax.swing.JLabel lblanvnamn;
    private javax.swing.JLabel lblmotesNamn;
    // End of variables declaration//GEN-END:variables
}
