/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blogapplication;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author Team 14
 */
public class BjudInTillMote extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;
    private int motesId;
    private String datum1;
    private String datum2;
    private String datum3;
    private String starttid1;
    private String starttid2;
    private String starttid3;
    private String sluttid1;
    private String sluttid2;
    private String sluttid3;

    /**
     * Creates new form BjudInTillMote
     */
    public BjudInTillMote(int motesId, String datum1, String datum2, String datum3, String starttid1, String starttid2, String starttid3,
            String sluttid1, String sluttid2, String sluttid3) {
        dataHanterare = new DataHanterare();
        databasen = DataHanterare.dataHanterare();
        this.setLocationRelativeTo(null);
        initComponents();
        this.motesId = motesId;
        this.datum1 = datum1;
        this.datum2 = datum2;
        this.datum3 = datum3;
        this.starttid1 = starttid1;
        this.starttid2 = starttid2;
        this.starttid3 = starttid3;
        this.sluttid1 = sluttid1;
        this.sluttid2 = sluttid2;
        this.sluttid3 = sluttid3;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbAnvandare = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Bjud in personer till ditt möte");

        cmbAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnvandareActionPerformed(evt);
            }
        });

        jButton1.setText("Lägg till");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Klar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(cmbAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnvandareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAnvandareActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cmbAnvandare.removeAllItems();
        dataHanterare.fyllCmbAnvandarnamn(cmbAnvandare);

    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String anvandare = cmbAnvandare.getSelectedItem().toString();
        String[] namnet = anvandare.split(" ");
        String fornamn = namnet[0].toString();
        String efternamn = namnet[1].toString();
        int anvId = dataHanterare.getAnvandarId(fornamn, efternamn);
        int forslagId = dataHanterare.getNextForslagId();
        int andraforslagId = forslagId + 1;
        int tredjeforslagId = andraforslagId + 2;
        boolean lyckats = dataHanterare.laggTillMotesForslag(anvId, motesId, forslagId, andraforslagId, tredjeforslagId,
                datum1, starttid1, sluttid1, datum2, starttid2, sluttid2, datum3, starttid3, sluttid3);
        if (lyckats) {
            JOptionPane.showMessageDialog(null, "Användaren " + anvandare + " har nu bjudits till detta möte!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAnvandare;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
