/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blogapplication;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Morhaf
 */
public class InbkoatMote extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;
    private String titel;
    private String arrangorFornamn;
    private String arrangorEfternamn;
    private String datumochtid;
    private String plats;
    private int userId;
    private int valtMote;
    /**
     * Creates new form InbkoatMote
     */
    public InbkoatMote(String titel, String arrangorFornamn, String arrangorEfternamn, String datumochtid, String plats, int valtMote, int userId) {
        dataHanterare = new DataHanterare();
        databasen = DataHanterare.dataHanterare();
        initComponents();
        this.setLocationRelativeTo(null);
        this.titel=titel;
         this.arrangorFornamn=arrangorFornamn;
          this.arrangorEfternamn=arrangorEfternamn;
           this.datumochtid=datumochtid;
           this.plats=plats;
           this.userId=userId;
           this.valtMote=valtMote;
           setText();
    }
    
    public void setText(){
    txtMotesInfo.setText("Mötet: \"" + titel + "\" hålls av " + arrangorFornamn + " " + arrangorEfternamn + ". \n" + datumochtid + " på platsen: " + plats+".");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMotesInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotesInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        chbMejl = new javax.swing.JCheckBox();
        chbSms = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMotesInfo.setText("MotesInfo:");

        txtMotesInfo.setEditable(false);
        txtMotesInfo.setColumns(20);
        txtMotesInfo.setRows(5);
        jScrollPane1.setViewportView(txtMotesInfo);

        jLabel1.setText("Vill du få påminnelse för detta möte?");

        chbMejl.setText("Via Mejl");

        chbSms.setText("Via SMS");

        jButton1.setText("Klar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMotesInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbMejl)
                        .addGap(44, 44, 44)
                        .addComponent(chbSms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMotesInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chbMejl)
                        .addComponent(chbSms)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      dataHanterare.setMotesNotis(userId, valtMote, "U");
      if(chbMejl.isSelected()){
      dataHanterare.setMotesNotis(userId, valtMote, "M");
      }
      if(chbSms.isSelected()){
      dataHanterare.setMotesNotis(userId, valtMote, "S");
      }
      
      if(chbSms.isSelected() && chbMejl.isSelected()){
      dataHanterare.setMotesNotis(userId, valtMote, "Y");
      }
      if(!chbSms.isSelected() && !chbMejl.isSelected()){
      dataHanterare.setMotesNotis(userId, valtMote, "N");
      }
      chbMejl.setSelected(false);
      chbSms.setSelected(false);
      JOptionPane.showMessageDialog(null, "Påminnelseinställningarna har sparats.");
      this.dispose();
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbMejl;
    private javax.swing.JCheckBox chbSms;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMotesInfo;
    private javax.swing.JTextArea txtMotesInfo;
    // End of variables declaration//GEN-END:variables
}
