/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blogapplication;

import java.util.ArrayList;
import oru.inf.InfDB;

/**
 *
 * @author Morhaf
 */
public class MinaSkapadeMoten extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;
    private int userId;
    private int motesId;

    /**
     * Creates new form BefentligtMote
     */
    public MinaSkapadeMoten(int userId, int motesId) {
        initComponents();
        dataHanterare = new DataHanterare();
        databasen = DataHanterare.dataHanterare();
        this.userId = userId;
        this.motesId = motesId;
        this.setLocationRelativeTo(null);
        setRubrik();
        fyllRespons();
    }

    public void setRubrik() {
        String anvandarNamn = dataHanterare.getFullNamn(userId);
        String motesNamn = dataHanterare.getMotesnamn(motesId);
        lblRubrik.setText("Välkommen " + anvandarNamn + ". Nedan ser du inbjudarnas respons för mötet: " + motesNamn);
    }

    public void fyllRespons() {
        String textAttSkrivaUt = "";

        ArrayList<String> allaInbjudna = dataHanterare.getDeltagarnasId(motesId);
        for (int i = 0; i < allaInbjudna.size(); i++) {
            String value = allaInbjudna.get(i);
            boolean harSvarat = dataHanterare.harSvaratInbjudan(motesId, value);
            if (!harSvarat) {
                textAttSkrivaUt = textAttSkrivaUt + dataHanterare.getInteSvaratRespons(value) + "\n";
            } else if(harSvarat) {
                ArrayList<String> fId = dataHanterare.getForslagId(motesId, value);
                for (String s : fId) {
                     System.out.println("det som skickas in "+ s);
                    textAttSkrivaUt += dataHanterare.getAnvandarRespons(s) + "\n";
                   
                }
            }
        }
        txaRespons.append(textAttSkrivaUt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRespons = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRubrik.setText("txt");

        txaRespons.setEditable(false);
        txaRespons.setColumns(20);
        txaRespons.setRows(5);
        jScrollPane1.setViewportView(txaRespons);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRubrik)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JTextArea txaRespons;
    // End of variables declaration//GEN-END:variables
}
