
package blogapplication;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * @author Parisa Mohammadi
 */
public class Notisinstallningar extends javax.swing.JFrame {

    private final DataHanterare dataHanterare;
    private final InfDB databasen;
    private String MejlAdress;
    private String userId;
   
    public Notisinstallningar(String userId) {
        initComponents();
        dataHanterare = new DataHanterare();
        databasen = DataHanterare.dataHanterare();
        MejlAdress = dataHanterare.getAnvandarnamn(userId);
        this.userId=userId;
        lblVlkmn.setText("Välkommen " + dataHanterare.getAnvandarFornamn(Integer.parseInt(userId)) + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chbFormell = new javax.swing.JCheckBox();
        chbUtbildning = new javax.swing.JCheckBox();
        btnSpara = new javax.swing.JButton();
        chbInformell = new javax.swing.JCheckBox();
        chbForskning = new javax.swing.JCheckBox();
        lblVlkmn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Jag önskar få epost-notifikationer:");

        chbFormell.setText("Vid nya inlägg i den formella bloggen");

        chbUtbildning.setText("Vid nya inlägg i utbildningsbloggen");

        btnSpara.setText("Spara Ändringar");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        chbInformell.setText("Vid nya inlägg i den informella bloggen");

        chbForskning.setText("Vid nya inlägg i forskningsbloggen");

        lblVlkmn.setText("vlkmn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbForskning)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbFormell)
                            .addComponent(btnSpara)
                            .addComponent(chbUtbildning))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVlkmn)
                            .addComponent(chbInformell))
                        .addGap(0, 287, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVlkmn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbFormell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbInformell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbUtbildning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbForskning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSpara)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        String AID = userId;
        dataHanterare.stangAvBloggNotiser(userId);
                if(chbFormell.isSelected()){
                    dataHanterare.faFormellNotiser(userId);  
                }
                if(chbInformell.isSelected()){
                dataHanterare.faInformellNotiser(userId); 
                }
                if(chbUtbildning.isSelected()){
                dataHanterare.faUtbildningNotiser(userId); 
                }
                if(chbForskning.isSelected()){
                dataHanterare.faForskningNotiser(userId); 
                }
    JOptionPane.showMessageDialog(null, "Dina ändringar har sparats!");
      chbFormell.setSelected(false);
      chbInformell.setSelected(false);
      chbForskning.setSelected(false);
      chbUtbildning.setSelected(false);
    }//GEN-LAST:event_btnSparaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JCheckBox chbFormell;
    private javax.swing.JCheckBox chbForskning;
    private javax.swing.JCheckBox chbInformell;
    private javax.swing.JCheckBox chbUtbildning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblVlkmn;
    // End of variables declaration//GEN-END:variables
}
