
package blogapplication;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * @author Parisa Mohammadi
 */
public class Notifikationsinställningar extends javax.swing.JFrame {

    private final DataHanterare dataHanterare;
    private final InfDB databasen;
    private String MejlAdress;
   
    public Notifikationsinställningar() {
        initComponents();
        dataHanterare = new DataHanterare();
        databasen = DataHanterare.dataHanterare();
        MejlAdress = dataHanterare.getAnvandarnamn();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        btnStangAv = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Jag önskar få notifikationer:");

        jCheckBox1.setText("Vid nya inlägg i det formella bloggen");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Vid nya inlägg vid det informella bloggen");

        jLabel3.setText("Tryck knappen nedan om du inte önskar notifikationer:");

        btnStangAv.setText("Stäng av");
        btnStangAv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStangAvActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara Ändringar");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStangAv)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(btnSpara))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(93, 93, 93)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStangAv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnSpara)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        String AID = " ";
        try{
         
            System.out.println(MejlAdress);
            AID = databasen.fetchSingle(" SELECT ANVANDARID FROM ANVANDARE WHERE MEJL = '" + MejlAdress + "' ");
            System.out.println(AID);
        }
        catch(InfException ex){
            System.out.println("AID kunde ej hittas!");
        }
        try{
            String query = databasen.fetchSingle("SELECT INLAGGID  FROM INLAGG WHERE SKRIBENT = '" + AID + "' AND BSEKTION = 1; "); 
            //SELECT NOTISID FROM NOTISER WHERE ANVANDARID = AID AND BLOGGSEKTIONID = 1
            System.out.println(query);
            if(query == null){
                if(jCheckBox1.isSelected()){
                    databasen.insert("INSERT INTO INLAGG (SKRIBENT,BSEKTION) VALUES (" + AID + " , 1); "); 
                     //INSERT INTO NOTISER (ANVANDARID,BLOGGSEKTIONID) VALUES(AID,1)
                   
                }
                    else{
                        if(!jCheckBox1.isSelected()){
                          databasen.delete("DELETE FROM INLAGG WHERE SKRIBENT = " + AID + " AND BSEKTION = 1; ");  
                    }
                }
       
            }
        }
        catch(InfException e){
            System.out.println(e);
        }
        
           try{
            String query = databasen.fetchSingle("SELECT INLAGGID FROM INLAGG WHERE SKRIBENT = " + AID + " AND BSEKTION = 2; ");
            System.out.println(query);
            if(query == null){
                if(jCheckBox2.isSelected()){
                    databasen.insert("INSERT INTO INLAGG (SKRIBENT,BSEKTION) VALUES (" + AID + " , 2); ");
                }
                    else{
                        if(!jCheckBox2.isSelected()){
                          databasen.delete("DELETE FROM INLAGG WHERE SKRIBENT = " + AID + " AND BSEKTION = 2; ");  
                    }
                }
       
            }
        }
        catch(InfException ex){
            System.out.println("något gick fel, försök igen!");
        }
           
           
       
    /*
    här behöver vi lagra notiser i en tabel som lagrar även mejladress. vi måste kunna veta vilken p
    */
//       private void updateEmail(String svar){
//           String AID = "";
//           String arNull = null;
//           
//           try{
//               AID = databasen.fetchSingle("SELECT ANVANDARID FROM ANVANDARE WHERE MEJL = '" +InloggadAnvandare.getAnvandarnamn()+"' ");
//               System.out.println(AID);
//               arNull = databasen.fetchSingle(" SELECT ANVANDARID FROM NOTISER WHERE ANVANDARID = '" + AID + "' ");
//               System.out.println(arNull);
//               
//               if(arNull == null){
//                   
//               }
//           }catch(InfException ex){
//           }
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnStangAvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStangAvActionPerformed
          try{String AID = databasen.fetchSingle(" SELECT ANVANDARID FROM ANVANDARE WHERE MEJL = '" + MejlAdress+"' ");
             databasen.delete("DELETE FROM INLAGG WHERE SKRIBENT = '"+ AID +"' ");
             JOptionPane.showMessageDialog(null, "Dina ändringar har sparats!");
          }
          catch(InfException e){
              JOptionPane.showMessageDialog(null, "kontrollera inmatningen");
          }
    }//GEN-LAST:event_btnStangAvActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnStangAv;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
