/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blogapplication;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author Morhaf
 */
public class PublikKalender extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;
    private int userId;
    private String valtDatum;

    /**
     * Creates new form PublikKalender
     */
    public PublikKalender(int userId) {
        initComponents();
        dataHanterare = new DataHanterare();
        databasen = DataHanterare.dataHanterare();
        this.setLocationRelativeTo(null);
        valtDatum = "NC";
        this.userId = userId;
        setVlkmnMdlnde();
    }

    public void setVlkmnMdlnde() {
        String anvnamn=dataHanterare.getFullNamn(userId);
        lblVlkmn.setText("Välkommen " + anvnamn + "! Välj ett datum för att visa möten vid den dagen");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        klndr = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        lblVlkmn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaInpMote = new javax.swing.JTextArea();
        btnVisaMoten = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel1.setText("Möteskalender");

        lblVlkmn.setText("Vlkmn");

        txaInpMote.setEditable(false);
        txaInpMote.setColumns(20);
        txaInpMote.setRows(5);
        txaInpMote.setText("Inget datum är valt.");
        jScrollPane1.setViewportView(txaInpMote);

        btnVisaMoten.setText("Visa möten");
        btnVisaMoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaMotenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(klndr, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVlkmn, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(btnVisaMoten)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVlkmn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(klndr, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisaMoten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisaMotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaMotenActionPerformed
        DateFormat formatDatum = new SimpleDateFormat("yyyy-MM-dd");
        String datumformat1 = formatDatum.format(klndr.getDate());
        this.valtDatum = datumformat1;
        if (this.valtDatum.trim().equals("NC")) {
            JOptionPane.showMessageDialog(null, "Du måste välja ett datum först!");
        } else {
            txaInpMote.setText("");
            String textAttSkrivaUt="";
            String datumet=valtDatum.trim();
            try{
            ArrayList<String> motesIdLista=dataHanterare.getPlaneradeMoten(datumet);
            if(motesIdLista.size()>0){
            for (String s:motesIdLista){
            String motesNamn=dataHanterare.getMotetsnamn(s);
            String motesArrangor=dataHanterare.getMotetsSkapareNamn(userId);
            String motesDatum=dataHanterare.getMotetsDatum(s);
            String motetsSluttid=dataHanterare.getMotetsSluttid(s).trim();
            String motetsStarttid=dataHanterare.getMotetsStarttid(s).trim();
            textAttSkrivaUt+="Mötet \""+motesNamn+"\" hålls av "+motesArrangor+", "+motesDatum+" kl "+motetsStarttid+"-"+motetsSluttid+".\n";
            }
            txaInpMote.append(textAttSkrivaUt);
            }
            else{
            txaInpMote.append("Det finns inga inplanerade möten vid detta datum.");
            }
            }
            catch(NullPointerException e){
            txaInpMote.append("Det finns inga inplanerade möten vid detta datum.");
            }
        }
    }//GEN-LAST:event_btnVisaMotenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisaMoten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JCalendar klndr;
    private javax.swing.JLabel lblVlkmn;
    private javax.swing.JTextArea txaInpMote;
    // End of variables declaration//GEN-END:variables
}
