/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blogapplication;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import sun.util.calendar.BaseCalendar;

/**
 *
 * @author Team 14
 */
public class SkapaMote extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;
    public int userId;
    public int valdInplnaerade;
    public int valdMotesInbjudanId;
    public int valdMoteMinaMoten;

    /**
     * Creates new form MotesBokning
     */
    public SkapaMote(int userId) {

        dataHanterare = new DataHanterare();
        databasen = DataHanterare.dataHanterare();
        this.userId = userId;
        initComponents();
        this.setLocationRelativeTo(null);
        valdMotesInbjudanId = -1;
        valdMoteMinaMoten = -1;
        valdInplnaerade = -1;
    }

    public void tomFalten() {
        tfTitel.setText("");
        tfPlats.setText("");
        tfStartTid1.setText("");
        tfSluttid1.setText("");
        tfStartTid2.setText("");
        tfStartTid3.setText("");
        tfSluttid2.setText("");
        tfSluttid3.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTitel = new javax.swing.JTextField();
        tfPlats = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dcDatum1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        tfStartTid2 = new javax.swing.JTextField();
        dcDatum3 = new com.toedter.calendar.JDateChooser();
        tfStartTid3 = new javax.swing.JTextField();
        tfStartTid1 = new javax.swing.JTextField();
        dcDatum2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfSluttid1 = new javax.swing.JTextField();
        tfSluttid2 = new javax.swing.JTextField();
        tfSluttid3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lMinaSkapadeMoten = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lMotesInbjud = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lIplaneradeMoten = new javax.swing.JList<>();
        btnVisaInplanerade = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnMotesStatus = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Skapa Möte");

        jLabel2.setText("Titel");

        jLabel3.setText("Plats");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Förslag på datum och tider");

        jLabel5.setText("Datum ");

        dcDatum1.setFocusable(false);
        dcDatum1.setRequestFocusEnabled(false);

        jLabel6.setText("Starttid");

        dcDatum3.setFocusable(false);
        dcDatum3.setRequestFocusEnabled(false);

        dcDatum2.setFocusable(false);
        dcDatum2.setRequestFocusEnabled(false);

        jLabel7.setText("HH.MM");

        jLabel8.setText("Sluttid");

        jLabel9.setText("HH.MM");

        jButton1.setText("Skapa möte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dcDatum1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcDatum2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcDatum3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfStartTid2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStartTid3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStartTid1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfPlats, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(tfTitel))))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfSluttid1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addComponent(tfSluttid2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfSluttid3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfStartTid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfSluttid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfStartTid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfSluttid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcDatum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcDatum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfStartTid3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfSluttid3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        lMinaSkapadeMoten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMinaSkapadeMotenMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lMinaSkapadeMoten);

        lMotesInbjud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMotesInbjudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lMotesInbjud);

        lIplaneradeMoten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lIplaneradeMotenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lIplaneradeMoten);

        btnVisaInplanerade.setText("Visa Inplanerade");
        btnVisaInplanerade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaInplaneradeActionPerformed(evt);
            }
        });

        jButton2.setText("Visa inbjudan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnMotesStatus.setText("Visa Mötesuppdatering");
        btnMotesStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotesStatusActionPerformed(evt);
            }
        });

        jLabel13.setText("Mina skapade möten status");

        jLabel10.setText("Mötesinbjudningar");

        jLabel11.setText("Inplanerade möten");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnMotesStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(73, 73, 73)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnVisaInplanerade)
                                .addGap(12, 12, 12)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(54, 54, 54))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisaInplanerade)
                    .addComponent(jButton2)
                    .addComponent(btnMotesStatus))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(527, 527, 527))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Validering.FaltArTom(tfTitel) || Validering.FaltArTom(tfPlats) || Validering.FaltArTom(tfStartTid1)
                || Validering.FaltArTom(tfSluttid1) || Validering.FaltArTom(tfStartTid2) || Validering.FaltArTom(tfStartTid3)
                || Validering.FaltArTom(tfSluttid3) || Validering.FaltArTom(tfSluttid2)) {
            System.out.println("Ett eller flera fält är tomma!");
        }

        //dataHanterare.stringFormat(tfInlogMail.getText());
        String datumformat1 = "";
        String datumformat2 = "";
        String datumformat3 = "";
        String titel = dataHanterare.stringFormat(tfTitel.getText());
        String plats = dataHanterare.stringFormat(tfPlats.getText());
        int motesId = dataHanterare.getNextMotesId();
        if (dataHanterare.skapaNyttMote(motesId, userId, "2000-01-01", "00.00", "00.00", titel, plats)) {
            System.err.println("Mötet har skapats");
        }
        DateFormat formatDatum = new SimpleDateFormat("yyyy-MM-dd");
        datumformat1 = formatDatum.format(dcDatum1.getDate());
        datumformat2 = formatDatum.format(dcDatum2.getDate());
        datumformat3 = formatDatum.format(dcDatum3.getDate());
        String starttid1 = tfStartTid1.getText();
        String starttid2 = tfStartTid2.getText();
        String starttid3 = tfStartTid3.getText();
        String sluttid1 = tfSluttid1.getText();
        String sluttid2 = tfSluttid2.getText();
        String sluttid3 = tfSluttid3.getText();

        new BjudInTillMote(motesId, datumformat1, datumformat2, datumformat3, starttid1, starttid2, starttid3, sluttid1, sluttid2, sluttid3).setVisible(true);
        tomFalten();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dataHanterare.fyllListInplaneradeMoten(userId, lIplaneradeMoten);
        dataHanterare.fyllListMotesInbjudningar(userId, lMotesInbjud);
        dataHanterare.fyllListaMinaSkapadeMoten(userId, lMinaSkapadeMoten);

    }//GEN-LAST:event_formWindowOpened

    private void lMotesInbjudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMotesInbjudMouseClicked
        String motesnamn = lMotesInbjud.getSelectedValue();
        this.valdMotesInbjudanId = dataHanterare.getMotesId(motesnamn);

    }//GEN-LAST:event_lMotesInbjudMouseClicked

    private void lIplaneradeMotenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lIplaneradeMotenMouseClicked
        String motesnamn = lIplaneradeMoten.getSelectedValue();
        this.valdInplnaerade = dataHanterare.getMotesId(motesnamn);
    }//GEN-LAST:event_lIplaneradeMotenMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (valdMotesInbjudanId != -1) {
            new AngeTillganglighet(userId, valdMotesInbjudanId).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Du måste välja en mötesinbjudan från listan!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lMinaSkapadeMotenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMinaSkapadeMotenMouseClicked
        String motesnamn = lMinaSkapadeMoten.getSelectedValue();
        this.valdMoteMinaMoten = dataHanterare.getMotesId(motesnamn);
    }//GEN-LAST:event_lMinaSkapadeMotenMouseClicked

    private void btnMotesStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotesStatusActionPerformed
        if (valdMoteMinaMoten != -1) {
            new MinaSkapadeMoten(userId, valdMoteMinaMoten).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Du måste välja ett befentligt möte från listan!");
        }
    }//GEN-LAST:event_btnMotesStatusActionPerformed

    private void btnVisaInplaneradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaInplaneradeActionPerformed
        if (valdInplnaerade != -1) {
            int MID = 0;
            String datum = "";
            String starttid = "";
            String sluttid = "";
            String plats = "";
            String arrangorFornamn = "";
            String arrangorEfternamn = "";
            String titel = "";
            String tid = "";
            String datumochtid = "";
            try {
                MID = valdInplnaerade;
                datum = databasen.fetchSingle("SELECT DATUM FROM MOTEN WHERE MotesId ='" + MID + "';");
                starttid = databasen.fetchSingle("SELECT starttid FROM MOTEN WHERE MotesId ='" + MID + "';");
                sluttid = databasen.fetchSingle("SELECT sluttid FROM MOTEN WHERE MotesId ='" + MID + "';");
                tid = starttid.trim() + "-" + sluttid.trim();
                datumochtid = datum + " " + tid;
                if (datum.equals("2000-01-01")) {
                    datum = "ob";
                }
                if (starttid.equalsIgnoreCase("00.00") || (sluttid.equalsIgnoreCase("00.00"))) {
                    tid = "ob";
                }
                if (datum.equalsIgnoreCase("ob") || tid.equalsIgnoreCase("ob")) {
                    datumochtid = " datum och tid är inte bestämda än,";
                }
                arrangorFornamn = databasen.fetchSingle("SELECT FORNAMN FROM ANVANDARE JOIN MOTEN ON ANVANDARE.ANVANDARID = MOTEN.ARRANGOR AND MOTEN.MOTESID ='" + MID + "';");
                arrangorEfternamn = databasen.fetchSingle("SELECT EFTERNAMN FROM ANVANDARE JOIN MOTEN ON ANVANDARE.ANVANDARID = MOTEN.ARRANGOR AND MOTEN.MOTESID ='" + MID + "';");
                titel = databasen.fetchSingle("SELECT titel FROM MOTEN WHERE MotesId ='" + MID + "';");
                plats = databasen.fetchSingle("SELECT plats FROM MOTEN WHERE MotesId ='" + MID + "';");

            } catch (InfException e) {

            }
            JOptionPane.showMessageDialog(null, "Mötet: " + titel + " hålls av " + arrangorFornamn + " " + arrangorEfternamn + " \n" + datumochtid + " på platsen: " + plats);
        } else {
            JOptionPane.showMessageDialog(null, "Du måste välja ett inplanerat möte från listan först!");
        }
    }//GEN-LAST:event_btnVisaInplaneradeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        dataHanterare.fyllListInplaneradeMoten(userId, lIplaneradeMoten);
        dataHanterare.fyllListMotesInbjudningar(userId, lMotesInbjud);
        dataHanterare.fyllListaMinaSkapadeMoten(userId, lMinaSkapadeMoten);
    }//GEN-LAST:event_formWindowActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMotesStatus;
    private javax.swing.JButton btnVisaInplanerade;
    private com.toedter.calendar.JDateChooser dcDatum1;
    private com.toedter.calendar.JDateChooser dcDatum2;
    private com.toedter.calendar.JDateChooser dcDatum3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lIplaneradeMoten;
    private javax.swing.JList<String> lMinaSkapadeMoten;
    private javax.swing.JList<String> lMotesInbjud;
    private javax.swing.JTextField tfPlats;
    private javax.swing.JTextField tfSluttid1;
    private javax.swing.JTextField tfSluttid2;
    private javax.swing.JTextField tfSluttid3;
    private javax.swing.JTextField tfStartTid1;
    private javax.swing.JTextField tfStartTid2;
    private javax.swing.JTextField tfStartTid3;
    private javax.swing.JTextField tfTitel;
    // End of variables declaration//GEN-END:variables
}
