/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blogapplication;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import oru.inf.InfDB;

/**
 *
 * @author Team 14
 */
public class VisaBloggInlagg extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;
    private Box box;
    private int userId;

    /**
     * Creates new form VisaInlagg
     */
    public VisaBloggInlagg(int userId) {
        initComponents();
        dataHanterare = new DataHanterare();
        databasen = DataHanterare.dataHanterare();
        this.setLocationRelativeTo(null);
        box = new Box(BoxLayout.Y_AXIS);
        jScrollPane1.setViewportView(box);
        this.userId = userId;
        SetBorders();
        setVlkmn();
    }

    public void SetBorders() {
        Border b = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.blue);
        lblFormellB.setBorder(b);
        lblForskningB.setBorder(b);
        lblInformellB.setBorder(b);
        lblUtbildningB.setBorder(b);
    }

    public void setVlkmn() {

        lblVlkmn.setText("Välkommen " + dataHanterare.getFullNamn(userId) + "! Klicka på en bloggsektion för att visa inläggen!");
    }

    public void VisaFormellBlogg() {
        jScrollPane1.repaint();
        box.removeAll();
        ArrayList IIDlista = dataHanterare.getFormellaInlaggId();
        try {
            if (IIDlista.size() > 0) {
                for (Object inlagg : IIDlista) {

                    JPanel importeradPanel = new EttInlagg(inlagg.toString());
                    importeradPanel.setVisible(true);
                    box.add(importeradPanel);
                    box.revalidate();
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Det finns inga inlägg på denna blogg än!");
        }
    }

    public void VisaInormellBlogg() {
        jScrollPane1.repaint();
        box.removeAll();
        ArrayList IIDlista = dataHanterare.getInformellaInlaggId();
        try {
            if (IIDlista.size() > 0) {
                for (Object inlagg : IIDlista) {

                    JPanel importeradPanel = new EttInlagg(inlagg.toString());
                    importeradPanel.setVisible(true);
                    box.add(importeradPanel);
                    box.revalidate();
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Det finns inga inlägg på denna blogg än!");
        }

    }

    public void VisaUtbildningInlagg() {
        jScrollPane1.repaint();
        box.removeAll();
        ArrayList IIDlista = dataHanterare.getUtbildningInlaggId();
        try {
            if (IIDlista.size() > 0) {
                for (Object inlagg : IIDlista) {

                    JPanel importeradPanel = new EttInlagg(inlagg.toString());
                    importeradPanel.setVisible(true);
                    box.add(importeradPanel);
                    box.revalidate();
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Det finns inga inlägg på denna blogg än!");
        }
    }

    public void VisaForskningInlagg() {
        jScrollPane1.repaint();
        box.removeAll();
        ArrayList IIDlista = dataHanterare.getForskningInlaggId();
        try {
            if (IIDlista.size() > 0) {
                for (Object inlagg : IIDlista) {

                    JPanel importeradPanel = new EttInlagg(inlagg.toString());
                    importeradPanel.setVisible(true);
                    box.add(importeradPanel);
                    box.revalidate();
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Det finns inga inlägg på denna blogg än!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lblVlkmn = new javax.swing.JLabel();
        lblInformellB = new javax.swing.JLabel();
        lblUtbildningB = new javax.swing.JLabel();
        lblForskningB = new javax.swing.JLabel();
        lblFormellB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfInlaggnr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnTaBortInlagg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblVlkmn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVlkmn.setText("Välkommen! Klicka på en bloggsektion för att visa inläggen!");

        lblInformellB.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        lblInformellB.setText("Informell blogg");
        lblInformellB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInformellBMouseClicked(evt);
            }
        });

        lblUtbildningB.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        lblUtbildningB.setText("Utbildning blogg");
        lblUtbildningB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUtbildningBMouseClicked(evt);
            }
        });

        lblForskningB.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        lblForskningB.setText("Forskning blogg");
        lblForskningB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForskningBMouseClicked(evt);
            }
        });

        lblFormellB.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        lblFormellB.setText("Fomell blogg");
        lblFormellB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFormellBMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel1.setText("Adminfunktioner");

        jLabel2.setText("Ange numret på inlägget som du vill ta bort");

        jLabel3.setText("Inlägg nummer");

        btnTaBortInlagg.setText("Ta bort inlägget");
        btnTaBortInlagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortInlaggActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVlkmn)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblFormellB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(lblInformellB, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblUtbildningB, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(lblForskningB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfInlaggnr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTaBortInlagg)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVlkmn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormellB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInformellB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUtbildningB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblForskningB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfInlaggnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(btnTaBortInlagg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblInformellBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformellBMouseClicked
        VisaInormellBlogg();
    }//GEN-LAST:event_lblInformellBMouseClicked

    private void lblUtbildningBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtbildningBMouseClicked
        VisaUtbildningInlagg();
    }//GEN-LAST:event_lblUtbildningBMouseClicked

    private void lblForskningBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForskningBMouseClicked
        VisaForskningInlagg();
    }//GEN-LAST:event_lblForskningBMouseClicked

    private void lblFormellBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFormellBMouseClicked
        VisaFormellBlogg();
    }//GEN-LAST:event_lblFormellBMouseClicked

    private void btnTaBortInlaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortInlaggActionPerformed
        System.out.println(userId);
        if (dataHanterare.arAdmin(userId)) {

            if (Validering.FaltArTom(tfInlaggnr) || !Validering.arHeltal(tfInlaggnr)) {
                System.out.println("Inmatning i fältet inläggnr är felaktig");
            } else {
                String inlaggnr = tfInlaggnr.getText();
                if (dataHanterare.inlaggFinns(inlaggnr)) {
                    if (dataHanterare.inlaggetHarFil(inlaggnr)) {
                        dataHanterare.taBortInlaggFil(inlaggnr);
                    }
                    dataHanterare.taBortInlagg(inlaggnr);
                    this.dispose();
                    new VisaBloggInlagg(userId).setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "Det finns inget inlägg med det angivna numret. \n Vänligen ange ett korrekt nummer och försök igen");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Du har inga adminrättigheter för att göra detta.");
        }

    }//GEN-LAST:event_btnTaBortInlaggActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBortInlagg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormellB;
    private javax.swing.JLabel lblForskningB;
    private javax.swing.JLabel lblInformellB;
    private javax.swing.JLabel lblUtbildningB;
    private javax.swing.JLabel lblVlkmn;
    private javax.swing.JTextField tfInlaggnr;
    // End of variables declaration//GEN-END:variables
}
